[options]

admin_passwd = CHANGE_MASTER_PASSWORD

db_host = localhost
db_port = 5432
db_user = myodoo11
db_password = CHANGE_ME

logfile = /var/log/myodoo11/myodoo11-server.log

addons_path = /opt/myodoo11/myodoo11/addons,/opt/myodoo11/myodoo11/custom_apps,/opt/myodoo11/myodoo11/test_apps

xmlrpc_port = 5511

log_db = True
log_db_level = warning
log_handler = :INFO
log_level = info

limit_request = 999999
limit_time_cpu = 999999
limit_time_real = 99999
